sudo: false
language: php

php:
  - 7.0

env:
  - REPORT_EXIT_STATUS=1 NO_INTERACTION=1 TESTS="--show-all

before_script:
  - phpize && ./configure --with-rlogd-src-dir=../rlogd/ && make

script:
  - make test | tee test-output.txt && grep 'TEST SUMMARY$' test-output.txt > /dev/null ; test $? '!=' 0

